import { FunctionComponent, PropsWithChildren } from "react";
import Head from "next/head";
import styles from "./Header.module.scss";

interface HeaderProps {
  nameOfPage: string;
}

const Header: FunctionComponent<PropsWithChildren<HeaderProps>> = ({
  nameOfPage,
  children,
}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.container}>{nameOfPage}</h1>
      {children}
    </>
  );
};

export default Header;
